apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
     name: eksymlcluster
     region: ap-south-1

nodeGroups:
     - name: ng1
       desiredCapacity: 2
       instanceType: t2.micro
     - name: ng2
       minSize: 2
       maxSize: 5
       instancesDistribution:
         instanceTypes: [ "t3.medium"] 
         onDemandBaseCapacity: 0
         onDemandPercentageAboveBaseCapacity: 50
         spotInstancePools: 2     
       ssh:
         publicKeyName: myeksnodekey