apiVersion: v1
kind: PersistentVolumeClaim
metadata:
     name: mypv-claim
spec: 
     storageClassName: "mysc"
     accessModes:
       - ReadWriteOnce
     resources:
       requests:
         storage: 10Gi